# Generated by Django 5.2.11 on 2026-03-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organizationaddress",
            old_name="address_id",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="historicalorganizationaddress",
            old_name="address_id",
            new_name="address",
        ),
        migrations.RemoveConstraint(
            model_name="organizationaddress",
            name="organization_address_unique_link",
        ),
        migrations.AlterField(
            model_name="organizationaddress",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_links",
                to="locations.address",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganizationaddress",
            name="address",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.address",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationaddress",
            constraint=models.UniqueConstraint(
                fields=("organization", "address", "address_type"),
                name="organization_address_unique_link",
            ),
        ),
    ]
