# Generated by Django 5.2.11 on 2026-03-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0003_historicalroleassignmentorganization_and_more"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentdetail",
            old_name="birth_country_id",
            new_name="birth_country",
        ),
        migrations.RenameField(
            model_name="studentdetail",
            old_name="birth_state_id",
            new_name="birth_state",
        ),
        migrations.RenameField(
            model_name="staffdetail",
            old_name="birth_country_id",
            new_name="birth_country",
        ),
        migrations.RenameField(
            model_name="staffdetail",
            old_name="birth_state_id",
            new_name="birth_state",
        ),
        migrations.RenameField(
            model_name="guardiandetail",
            old_name="birth_country_id",
            new_name="birth_country",
        ),
        migrations.RenameField(
            model_name="guardiandetail",
            old_name="birth_state_id",
            new_name="birth_state",
        ),
        migrations.RenameField(
            model_name="historicalstudentdetail",
            old_name="birth_country_id",
            new_name="birth_country",
        ),
        migrations.RenameField(
            model_name="historicalstudentdetail",
            old_name="birth_state_id",
            new_name="birth_state",
        ),
        migrations.RenameField(
            model_name="historicalstaffdetail",
            old_name="birth_country_id",
            new_name="birth_country",
        ),
        migrations.RenameField(
            model_name="historicalstaffdetail",
            old_name="birth_state_id",
            new_name="birth_state",
        ),
        migrations.RenameField(
            model_name="historicalguardiandetail",
            old_name="birth_country_id",
            new_name="birth_country",
        ),
        migrations.RenameField(
            model_name="historicalguardiandetail",
            old_name="birth_state_id",
            new_name="birth_state",
        ),
        migrations.AlterField(
            model_name="studentdetail",
            name="birth_country",
            field=models.ForeignKey(
                blank=True,
                help_text="Locations country reference for persona birth country.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_birth_country_records",
                to="locations.countrycode",
            ),
        ),
        migrations.AlterField(
            model_name="studentdetail",
            name="birth_state",
            field=models.ForeignKey(
                blank=True,
                help_text="Locations state reference for persona birth state.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_birth_state_records",
                to="locations.statecode",
            ),
        ),
        migrations.AlterField(
            model_name="staffdetail",
            name="birth_country",
            field=models.ForeignKey(
                blank=True,
                help_text="Locations country reference for persona birth country.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_birth_country_records",
                to="locations.countrycode",
            ),
        ),
        migrations.AlterField(
            model_name="staffdetail",
            name="birth_state",
            field=models.ForeignKey(
                blank=True,
                help_text="Locations state reference for persona birth state.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_birth_state_records",
                to="locations.statecode",
            ),
        ),
        migrations.AlterField(
            model_name="guardiandetail",
            name="birth_country",
            field=models.ForeignKey(
                blank=True,
                help_text="Locations country reference for persona birth country.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_birth_country_records",
                to="locations.countrycode",
            ),
        ),
        migrations.AlterField(
            model_name="guardiandetail",
            name="birth_state",
            field=models.ForeignKey(
                blank=True,
                help_text="Locations state reference for persona birth state.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_birth_state_records",
                to="locations.statecode",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstudentdetail",
            name="birth_country",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Locations country reference for persona birth country.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.countrycode",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstudentdetail",
            name="birth_state",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Locations state reference for persona birth state.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.statecode",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstaffdetail",
            name="birth_country",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Locations country reference for persona birth country.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.countrycode",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstaffdetail",
            name="birth_state",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Locations state reference for persona birth state.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.statecode",
            ),
        ),
        migrations.AlterField(
            model_name="historicalguardiandetail",
            name="birth_country",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Locations country reference for persona birth country.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.countrycode",
            ),
        ),
        migrations.AlterField(
            model_name="historicalguardiandetail",
            name="birth_state",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Locations state reference for persona birth state.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.statecode",
            ),
        ),
    ]
