# Generated by Django 5.2.11 on 2026-03-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0004_swap_birth_placeholders_to_locations_fks"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="mfa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
