# Generated by Django 5.2.11 on 2026-03-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0005_historicaluser_mfa_enabled_user_mfa_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="auth_session_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="auth_session_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
