STATE_CODE_SEEDS = [
    {"code": "AL", "label": "Alabama", "sort_order": 10},
    {"code": "AK", "label": "Alaska", "sort_order": 20},
    {"code": "AZ", "label": "Arizona", "sort_order": 30},
    {"code": "AR", "label": "Arkansas", "sort_order": 40},
    {"code": "CA", "label": "California", "sort_order": 50},
    {"code": "CO", "label": "Colorado", "sort_order": 60},
    {"code": "CT", "label": "Connecticut", "sort_order": 70},
    {"code": "DE", "label": "Delaware", "sort_order": 80},
    {"code": "DC", "label": "District of Columbia", "sort_order": 90},
    {"code": "FL", "label": "Florida", "sort_order": 100},
    {"code": "GA", "label": "Georgia", "sort_order": 110},
    {"code": "HI", "label": "Hawaii", "sort_order": 120},
    {"code": "ID", "label": "Idaho", "sort_order": 130},
    {"code": "IL", "label": "Illinois", "sort_order": 140},
    {"code": "IN", "label": "Indiana", "sort_order": 150},
    {"code": "IA", "label": "Iowa", "sort_order": 160},
    {"code": "KS", "label": "Kansas", "sort_order": 170},
    {"code": "KY", "label": "Kentucky", "sort_order": 180},
    {"code": "LA", "label": "Louisiana", "sort_order": 190},
    {"code": "ME", "label": "Maine", "sort_order": 200},
    {"code": "MD", "label": "Maryland", "sort_order": 210},
    {"code": "MA", "label": "Massachusetts", "sort_order": 220},
    {"code": "MI", "label": "Michigan", "sort_order": 230},
    {"code": "MN", "label": "Minnesota", "sort_order": 240},
    {"code": "MS", "label": "Mississippi", "sort_order": 250},
    {"code": "MO", "label": "Missouri", "sort_order": 260},
    {"code": "MT", "label": "Montana", "sort_order": 270},
    {"code": "NE", "label": "Nebraska", "sort_order": 280},
    {"code": "NV", "label": "Nevada", "sort_order": 290},
    {"code": "NH", "label": "New Hampshire", "sort_order": 300},
    {"code": "NJ", "label": "New Jersey", "sort_order": 310},
    {"code": "NM", "label": "New Mexico", "sort_order": 320},
    {"code": "NY", "label": "New York", "sort_order": 330},
    {"code": "NC", "label": "North Carolina", "sort_order": 340},
    {"code": "ND", "label": "North Dakota", "sort_order": 350},
    {"code": "OH", "label": "Ohio", "sort_order": 360},
    {"code": "OK", "label": "Oklahoma", "sort_order": 370},
    {"code": "OR", "label": "Oregon", "sort_order": 380},
    {"code": "PA", "label": "Pennsylvania", "sort_order": 390},
    {"code": "RI", "label": "Rhode Island", "sort_order": 400},
    {"code": "SC", "label": "South Carolina", "sort_order": 410},
    {"code": "SD", "label": "South Dakota", "sort_order": 420},
    {"code": "TN", "label": "Tennessee", "sort_order": 430},
    {"code": "TX", "label": "Texas", "sort_order": 440},
    {"code": "UT", "label": "Utah", "sort_order": 450},
    {"code": "VT", "label": "Vermont", "sort_order": 460},
    {"code": "VA", "label": "Virginia", "sort_order": 470},
    {"code": "WA", "label": "Washington", "sort_order": 480},
    {"code": "WV", "label": "West Virginia", "sort_order": 490},
    {"code": "WI", "label": "Wisconsin", "sort_order": 500},
    {"code": "WY", "label": "Wyoming", "sort_order": 510},
]
